version: '2'
services:
  ros-master:
    image: gramaziokohler/ros-tum-assembly-demo
    container_name: ros-master
    ports:
      - "11311:11311"
    command:
      - roscore

  ros-bridge:
    image: gramaziokohler/ros-tum-assembly-demo
    container_name: ros-bridge
    environment:
      - "ROS_HOSTNAME=ros-bridge"
      - "ROS_MASTER_URI=http://ros-master:11311"
    ports:
      - "80:80"
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - rosbridge_server
      - rosbridge_websocket.launch
      - port:=80
      - unregister_timeout:=28800      # This horribly long timeout of 8 hours is to workaround this issue: https://github.com/RobotWebTools/rosbridge_suite/issues/138

  ros-fileserver:
    image: gramaziokohler/ros-tum-assembly-demo
    container_name: ros-fileserver
    environment:
      - ROS_HOSTNAME=ros-fileserver
      - ROS_MASTER_URI=http://ros-master:11311
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - file_server
      - file_server.launch

  ur-demo:
    image: gramaziokohler/ros-tum-assembly-demo
    container_name: ur-demo
    environment:
      - ROS_HOSTNAME=ur-demo
      - ROS_MASTER_URI=http://ros-master:11311
      - DISPLAY=gui:0.0
    depends_on:
      - ros-master
      - gui
    command:
      - roslaunch
      - --wait
      - ur10_e_moveit_config
      - demo.launch

  gui:
    image: gramaziokohler/novnc:latest
    ports:
      - "8080:8080"
